export const all = [
  {
    id: 1,
    title: "ENDESS",
    mainImg: "assets/proImg/social/1/1.jpg",
    brandLogo: "assets/proImg/social/1/logo.png",
    secondImgs: [
      { id: 1, secondImg: "assets/proImg/social/1/1.jpg" },
      { id: 2, secondImg: "assets/proImg/social/1/2.jpg" },
    ],
    link: "https://www.behance.net/gallery/137602255/Social-Media-Design-about-ENDESS",
    desc: "It is a restaurant that sells different burgers in terms of size and taste and achieving the difficult equation of taste, size and price",
  },
  {
    id: 2,
    title: "Granhair",
    mainImg: "assets/proImg/social/2/1.jpg",
    brandLogo: "assets/proImg/social/2/logo.png",
    secondImgs: [
      { id: 1, secondImg: "assets/proImg/social/2/1.jpg" },
      { id: 2, secondImg: "assets/proImg/social/2/2.jpg" },
      { id: 3, secondImg: "assets/proImg/social/2/3.jpg" },
      { id: 4, secondImg: "assets/proImg/social/2/4.jpg" },
      { id: 5, secondImg: "assets/proImg/social/2/5.jpg" },
      { id: 6, secondImg: "assets/proImg/social/2/6.jpg" },
      { id: 7, secondImg: "assets/proImg/social/2/7.jpg" },
    ],
    link: "https://www.behance.net/gallery/137602011/Social-Media-Design-about-Granhair",
    desc: "is a hair products company affiliated with octipharma and targeting the UAE market",
  },
  {
    id: 3,
    title: "Arena sport",
    mainImg: "assets/proImg/social/3/1.jpg",
    brandLogo: "assets/proImg/social/3/logo.png",
    secondImgs: [
      { id: 1, secondImg: "assets/proImg/social/3/1.jpg" },
      { id: 2, secondImg: "assets/proImg/social/3/2.jpg" },
      { id: 3, secondImg: "assets/proImg/social/3/3.jpg" },
      { id: 4, secondImg: "assets/proImg/social/3/4.jpg" },
      { id: 5, secondImg: "assets/proImg/social/3/5.jpg" },
    ],
    link: "https://www.behance.net/gallery/137601581/Social-Media-Design-about-arenasport",
    desc: "It is an online store that sells original sports clothing and products such as adidas, nike and puma",
  },
  {
    id: 4,
    title: "the book group",
    mainImg: "assets/proImg/social/4/1.jpg",
    brandLogo: "assets/proImg/social/4/logo.png",
    secondImgs: [
      { id: 1, secondImg: "assets/proImg/social/4/1.jpg" },
      { id: 2, secondImg: "assets/proImg/social/4/2.jpg" },
      { id: 3, secondImg: "assets/proImg/social/4/3.jpg" },
      { id: 4, secondImg: "assets/proImg/social/4/4.jpg" },
      { id: 5, secondImg: "assets/proImg/social/4/5.jpg" },
    ],
    link: "https://www.behance.net/gallery/137601057/Social-Media-Design-about-Bebek-group",
    desc: "The Bebek group is rich in natural oils, where the Bebek soap works to eliminate bacteria and germs, and the cream works to moisturize and nourish the baby's skin.",
  },
  {
    id: 5,
    title: "NT3LM L",
    mainImg: "assets/proImg/social/5/1.jpg",
    brandLogo: "assets/proImg/social/5/logo.png",
    secondImgs: [
      { id: 1, secondImg: "assets/proImg/social/5/1.jpg" },
      { id: 2, secondImg: "assets/proImg/social/5/2.jpg" },
      { id: 3, secondImg: "assets/proImg/social/5/3.jpg" },
      { id: 4, secondImg: "assets/proImg/social/5/4.jpg" },
      { id: 5, secondImg: "assets/proImg/social/5/5.jpg" },
      { id: 6, secondImg: "assets/proImg/social/5/6.jpg" },
      { id: 7, secondImg: "assets/proImg/social/5/7.jpg" },
      { id: 8, secondImg: "assets/proImg/social/5/8.jpg" },
    ],
    link: "https://www.behance.net/gallery/137600751/Social-Media-Design-about-NT3LM",
    desc: "It is an integrated education system for teaching all levels of education through the NT3LM L website and through the Mobile Application",
  },
  {
    id: 6,
    title: "Cairo Data Flow",
    mainImg: "assets/proImg/social/6/1.jpg",
    brandLogo: "assets/proImg/social/6/logo.png",
    secondImgs: [
      { id: 1, secondImg: "assets/proImg/social/6/1.jpg" },
      { id: 2, secondImg: "assets/proImg/social/6/2.jpg" },
      { id: 3, secondImg: "assets/proImg/social/6/3.jpg" },
      { id: 4, secondImg: "assets/proImg/social/6/4.jpg" },
      { id: 5, secondImg: "assets/proImg/social/6/5.jpg" },
      { id: 6, secondImg: "assets/proImg/social/6/6.jpg" },
    ],
    link: "https://www.behance.net/gallery/137600337/Social-Media-Design-about-Cairo-Data-Flow",
    desc: "It is a travel company for doctors, nurses and technicians to the Arab Gulf countries through Prometric and Dataflow certificates.",
  },
  {
    id: 7,
    title: "Search Engine Optimization",
    mainImg: "assets/proImg/social/7/1.jpg",
    brandLogo: "assets/proImg/social/7/logo.png",
    secondImgs: [
      { id: 1, secondImg: "assets/proImg/social/7/1.jpg" },
      { id: 2, secondImg: "assets/proImg/social/7/2.jpg" },
    ],
    link: "https://www.behance.net/gallery/137600037/Social-Media-Design-about-Spider-seo",
    desc: "The science of improving the appearance of a website or website page in the results of free search engines such as Google so that it appears in the first results",
  },
  {
    id: 8,
    title: "Brand Factor",
    mainImg: "assets/proImg/social/8/1.jpg",
    brandLogo: "assets/proImg/social/8/logo.png",
    secondImgs: [
      { id: 1, secondImg: "assets/proImg/social/8/1.jpg" },
      { id: 2, secondImg: "assets/proImg/social/8/2.jpg" },
      { id: 3, secondImg: "assets/proImg/social/8/3.jpg" },
      { id: 4, secondImg: "assets/proImg/social/8/4.jpg" },
      { id: 5, secondImg: "assets/proImg/social/8/5.jpg" },
    ],
    link: "https://www.behance.net/gallery/137599733/Social-Media-Design-about-marketing-agency",
    desc: "it is a Marketing Agency to provide all marketing services for products such as (Photography - Graphic Designs - Motion Graphics - E-Marketing)",
  },
  {
    id: 9,
    title: "Heba Abdullah",
    mainImg: "assets/proImg/social/9/1.jpg",
    brandLogo: "assets/proImg/social/9/logo.png",
    secondImgs: [{ id: 1, secondImg: "assets/proImg/social/9/1.jpg" }],
    link: "https://www.behance.net/gallery/137598293/Social-Media-Design-about-fibromyalgia",
    desc: "Orthopedic and joint doctor",
  },
  {
    id: 10,
    title: "Cairo Data Flow",
    mainImg: "assets/proImg/social/10/1.jpg",
    brandLogo: "",
    secondImgs: [
      { id: 1, secondImg: "assets/proImg/social/10/1.jpg" },
      { id: 2, secondImg: "assets/proImg/social/10/2.jpg" },
      { id: 3, secondImg: "assets/proImg/social/10/3.jpg" },
    ],
    link: "https://www.behance.net/gallery/137598083/Social-Media-Design",
    desc: "It is a travel company for doctors, nurses and technicians to the Arab Gulf countries through Prometric and Dataflow certificates.",
  },
  {
    id: 10,
    title: "SND",
    mainImg: "assets/proImg/logos/1/1.jpg",
    secondImgs: [
      { id: 1, secondImg: "assets/proImg/logos/1/1.jpg" },
      { id: 2, secondImg: "assets/proImg/logos/1/2.jpg" },
      { id: 3, secondImg: "assets/proImg/logos/1/3.jpg" },
      { id: 4, secondImg: "assets/proImg/logos/1/4.jpg" },
      { id: 5, secondImg: "assets/proImg/logos/1/5.jpg" },
      { id: 6, secondImg: "assets/proImg/logos/1/6.jpg" },
    ],
    link: "https://www.behance.net/gallery/137597647/SND-logo",
    desc: "A start-up real estate company whose goal is to expand and open branches in such a place",
  },
  {
    id: 11,
    title: "Brand Factor",
    mainImg: "assets/proImg/logos/2/1.jpg",
    secondImgs: [
      { id: 1, secondImg: "assets/proImg/logos/2/1.jpg" },
      { id: 2, secondImg: "assets/proImg/logos/2/2.png" },
      { id: 3, secondImg: "assets/proImg/logos/2/3.jpg" },
      { id: 4, secondImg: "assets/proImg/logos/2/4.jpg" },
      { id: 5, secondImg: "assets/proImg/logos/2/5.jpg" },
    ],
    link: "https://www.behance.net/gallery/137597355/Marketing-Agency",
    desc: "it is a Marketing Agency to provide all marketing services for products such as (Photography - Graphic Designs - Motion Graphics - E-Marketing)",
  },
  {
    id: 12,
    title: "moony",
    mainImg: "assets/proImg/logos/3/1.jpg",
    secondImgs: [
      { id: 1, secondImg: "assets/proImg/logos/3/1.jpg" },
      { id: 2, secondImg: "assets/proImg/logos/3/2.jpg" },
      { id: 3, secondImg: "assets/proImg/logos/3/3.jpg" },
      { id: 4, secondImg: "assets/proImg/logos/3/4.jpg" },
      { id: 5, secondImg: "assets/proImg/logos/3/5.png" },
    ],
    link: "https://www.behance.net/gallery/137596569/lenses-Brand-logo",
    desc: "lenses Brand",
  },
  {
    id: 13,
    title: "Clouds",
    mainImg: "assets/proImg/logos/4/1.jpg",
    secondImgs: [
      { id: 1, secondImg: "assets/proImg/logos/4/1.jpg" },
      { id: 2, secondImg: "assets/proImg/logos/4/2.jpg" },
      { id: 3, secondImg: "assets/proImg/logos/4/3.png" },
      { id: 4, secondImg: "assets/proImg/logos/4/4.png" },
    ],
    link: "https://www.behance.net/gallery/137595141/Beauty-salon",
    desc: "It is a beauty salon",
  },
  {
    id: 14,
    title: "Technical solutions",
    mainImg: "assets/proImg/logos/5/1.jpg",
    secondImgs: [
      { id: 1, secondImg: "assets/proImg/logos/5/1.jpg" },
      { id: 2, secondImg: "assets/proImg/logos/5/2.jpg" },
      { id: 3, secondImg: "assets/proImg/logos/5/3.png" },
      { id: 4, secondImg: "assets/proImg/logos/5/4.jpg" },
      { id: 5, secondImg: "assets/proImg/logos/5/5.jpg" },
      { id: 6, secondImg: "assets/proImg/logos/5/6.png" },
    ],
    link: "https://www.behance.net/gallery/137594859/technical-solutions-logo",
    desc: "It is a company that provides administrative and technical consultancy, formulation and implementation of restructuring plans and administrative organization",
  },
  {
    id: 15,
    title: "osam",
    mainImg: "assets/proImg/logos/6/1.jpg",
    secondImgs: [
      { id: 1, secondImg: "assets/proImg/logos/6/1.jpg" },
      { id: 2, secondImg: "assets/proImg/logos/6/2.jpg" },
      { id: 3, secondImg: "assets/proImg/logos/6/3.jpg" },
      { id: 4, secondImg: "assets/proImg/logos/6/4.jpg" },
      { id: 5, secondImg: "assets/proImg/logos/6/5.jpg" },
      { id: 6, secondImg: "assets/proImg/logos/6/6.jpg" },
    ],
    link: "https://www.behance.net/gallery/137594229/Candies-shop-logo",
    desc: "A sweets shop that serves sweets and hot drinks",
  },
  {
    id: 16,
    title: "Medrex cream",
    mainImg: "assets/proImg/Labels/1/1.jpg",
    brandLogo: "assets/proImg/Labels/1/logo.png",
    secondImgs: [
      { id: 1, secondImg: "assets/proImg/Labels/1/1.jpg" },
      { id: 2, secondImg: "assets/proImg/Labels/1/2.jpg" },
    ],
    link: "http:",
    desc: "massage cream",
  },
  {
    id: 17,
    title: "vito ointmen",
    mainImg: "assets/proImg/Labels/2/1.png",
    brandLogo: "assets/proImg/Labels/2/logo.png",
    secondImgs: [
      { id: 1, secondImg: "assets/proImg/Labels/2/1.png" },
      { id: 2, secondImg: "assets/proImg/Labels/2/2.jpg" },
    ],
    link: "http:",
    desc: "ointment for skin care produced by Shifa Al sharkia Medical Establishment.",
  },
  {
    id: 18,
    title: "Sakkara",
    mainImg: "assets/proImg/Labels/3/1.jpg",
    brandLogo: "assets/proImg/Labels/3/logo.png",
    secondImgs: [
      { id: 1, secondImg: "assets/proImg/Labels/3/1.jpg" },
      { id: 2, secondImg: "assets/proImg/Labels/3/2.jpg" },
      { id: 3, secondImg: "assets/proImg/Labels/3/3.jpg" },
      { id: 4, secondImg: "assets/proImg/Labels/3/4.jpg" },
      { id: 5, secondImg: "assets/proImg/Labels/3/5.jpg" },
      { id: 6, secondImg: "assets/proImg/Labels/3/6.jpg" },
    ],
    link: "http:",
    desc: "It is a company that produces natural oils to treat dental problems",
  },
];

export const socialMediaDesign = [
  {
    id: 1,
    title: "ENDESS",
    mainImg: "assets/proImg/social/1/1.jpg",
    brandLogo: "assets/proImg/social/1/logo.png",
    secondImgs: [
      { id: 1, secondImg: "assets/proImg/social/1/1.jpg" },
      { id: 2, secondImg: "assets/proImg/social/1/2.jpg" },
    ],
    link: "https://www.behance.net/gallery/137602255/Social-Media-Design-about-ENDESS",
    desc: "It is a restaurant that sells different burgers in terms of size and taste and achieving the difficult equation of taste, size and price",
  },
  {
    id: 2,
    title: "Granhair",
    mainImg: "assets/proImg/social/2/1.jpg",
    brandLogo: "assets/proImg/social/2/logo.png",
    secondImgs: [
      { id: 1, secondImg: "assets/proImg/social/2/1.jpg" },
      { id: 2, secondImg: "assets/proImg/social/2/2.jpg" },
      { id: 3, secondImg: "assets/proImg/social/2/3.jpg" },
      { id: 4, secondImg: "assets/proImg/social/2/4.jpg" },
      { id: 5, secondImg: "assets/proImg/social/2/5.jpg" },
      { id: 6, secondImg: "assets/proImg/social/2/6.jpg" },
      { id: 7, secondImg: "assets/proImg/social/2/7.jpg" },
    ],
    link: "https://www.behance.net/gallery/137602011/Social-Media-Design-about-Granhair",
    desc: "is a hair products company affiliated with octipharma and targeting the UAE market",
  },
  {
    id: 3,
    title: "Arena sport",
    mainImg: "assets/proImg/social/3/1.jpg",
    brandLogo: "assets/proImg/social/3/logo.png",
    secondImgs: [
      { id: 1, secondImg: "assets/proImg/social/3/1.jpg" },
      { id: 2, secondImg: "assets/proImg/social/3/2.jpg" },
      { id: 3, secondImg: "assets/proImg/social/3/3.jpg" },
      { id: 4, secondImg: "assets/proImg/social/3/4.jpg" },
      { id: 5, secondImg: "assets/proImg/social/3/5.jpg" },
    ],
    link: "https://www.behance.net/gallery/137601581/Social-Media-Design-about-arenasport",
    desc: "It is an online store that sells original sports clothing and products such as adidas, nike and puma",
  },
  {
    id: 4,
    title: "the book group",
    mainImg: "assets/proImg/social/4/1.jpg",
    brandLogo: "assets/proImg/social/4/logo.png",
    secondImgs: [
      { id: 1, secondImg: "assets/proImg/social/4/1.jpg" },
      { id: 2, secondImg: "assets/proImg/social/4/2.jpg" },
      { id: 3, secondImg: "assets/proImg/social/4/3.jpg" },
      { id: 4, secondImg: "assets/proImg/social/4/4.jpg" },
      { id: 5, secondImg: "assets/proImg/social/4/5.jpg" },
    ],
    link: "https://www.behance.net/gallery/137601057/Social-Media-Design-about-Bebek-group",
    desc: "The Bebek group is rich in natural oils, where the Bebek soap works to eliminate bacteria and germs, and the cream works to moisturize and nourish the baby's skin.",
  },
  {
    id: 5,
    title: "NT3LM L",
    mainImg: "assets/proImg/social/5/1.jpg",
    brandLogo: "assets/proImg/social/5/logo.png",
    secondImgs: [
      { id: 1, secondImg: "assets/proImg/social/5/1.jpg" },
      { id: 2, secondImg: "assets/proImg/social/5/2.jpg" },
      { id: 3, secondImg: "assets/proImg/social/5/3.jpg" },
      { id: 4, secondImg: "assets/proImg/social/5/4.jpg" },
      { id: 5, secondImg: "assets/proImg/social/5/5.jpg" },
      { id: 6, secondImg: "assets/proImg/social/5/6.jpg" },
      { id: 7, secondImg: "assets/proImg/social/5/7.jpg" },
      { id: 8, secondImg: "assets/proImg/social/5/8.jpg" },
    ],
    link: "https://www.behance.net/gallery/137600751/Social-Media-Design-about-NT3LM",
    desc: "It is an integrated education system for teaching all levels of education through the NT3LM L website and through the Mobile Application",
  },
  {
    id: 6,
    title: "Cairo Data Flow",
    mainImg: "assets/proImg/social/6/1.jpg",
    brandLogo: "assets/proImg/social/6/logo.png",
    secondImgs: [
      { id: 1, secondImg: "assets/proImg/social/6/1.jpg" },
      { id: 2, secondImg: "assets/proImg/social/6/2.jpg" },
      { id: 3, secondImg: "assets/proImg/social/6/3.jpg" },
      { id: 4, secondImg: "assets/proImg/social/6/4.jpg" },
      { id: 5, secondImg: "assets/proImg/social/6/5.jpg" },
      { id: 6, secondImg: "assets/proImg/social/6/6.jpg" },
    ],
    link: "https://www.behance.net/gallery/137600337/Social-Media-Design-about-Cairo-Data-Flow",
    desc: "It is a travel company for doctors, nurses and technicians to the Arab Gulf countries through Prometric and Dataflow certificates.",
  },
  {
    id: 7,
    title: "Search Engine Optimization",
    mainImg: "assets/proImg/social/7/1.jpg",
    brandLogo: "assets/proImg/social/7/logo.png",
    secondImgs: [
      { id: 1, secondImg: "assets/proImg/social/7/1.jpg" },
      { id: 2, secondImg: "assets/proImg/social/7/2.jpg" },
    ],
    link: "https://www.behance.net/gallery/137600037/Social-Media-Design-about-Spider-seo",
    desc: "The science of improving the appearance of a website or website page in the results of free search engines such as Google so that it appears in the first results",
  },
  {
    id: 8,
    title: "Brand Factor",
    mainImg: "assets/proImg/social/8/1.jpg",
    brandLogo: "assets/proImg/social/8/logo.png",
    secondImgs: [
      { id: 1, secondImg: "assets/proImg/social/8/1.jpg" },
      { id: 2, secondImg: "assets/proImg/social/8/2.jpg" },
      { id: 3, secondImg: "assets/proImg/social/8/3.jpg" },
      { id: 4, secondImg: "assets/proImg/social/8/4.jpg" },
      { id: 5, secondImg: "assets/proImg/social/8/5.jpg" },
    ],
    link: "https://www.behance.net/gallery/137599733/Social-Media-Design-about-marketing-agency",
    desc: "it is a Marketing Agency to provide all marketing services for products such as (Photography - Graphic Designs - Motion Graphics - E-Marketing)",
  },
  {
    id: 9,
    title: "Heba Abdullah",
    mainImg: "assets/proImg/social/9/1.jpg",
    brandLogo: "assets/proImg/social/9/logo.png",
    secondImgs: [{ id: 1, secondImg: "assets/proImg/social/9/1.jpg" }],
    link: "https://www.behance.net/gallery/137598293/Social-Media-Design-about-fibromyalgia",
    desc: "Orthopedic and joint doctor",
  },
  {
    id: 10,
    title: "Cairo Data Flow",
    mainImg: "assets/proImg/social/10/1.jpg",
    brandLogo: "",
    secondImgs: [
      { id: 1, secondImg: "assets/proImg/social/10/1.jpg" },
      { id: 2, secondImg: "assets/proImg/social/10/2.jpg" },
      { id: 3, secondImg: "assets/proImg/social/10/3.jpg" },
    ],
    link: "https://www.behance.net/gallery/137598083/Social-Media-Design",
    desc: "It is a travel company for doctors, nurses and technicians to the Arab Gulf countries through Prometric and Dataflow certificates.",
  },
];

export const logo = [
  {
    id: 1,
    title: "SND",
    mainImg: "assets/proImg/logos/1/1.jpg",
    secondImgs: [
      { id: 1, secondImg: "assets/proImg/logos/1/1.jpg" },
      { id: 2, secondImg: "assets/proImg/logos/1/2.jpg" },
      { id: 3, secondImg: "assets/proImg/logos/1/3.jpg" },
      { id: 4, secondImg: "assets/proImg/logos/1/4.jpg" },
      { id: 5, secondImg: "assets/proImg/logos/1/5.jpg" },
      { id: 6, secondImg: "assets/proImg/logos/1/6.jpg" },
    ],
    link: "https://www.behance.net/gallery/137597647/SND-logo",
    desc: "A start-up real estate company whose goal is to expand and open branches in such a place",
  },
  {
    id: 2,
    title: "Brand Factor",
    mainImg: "assets/proImg/logos/2/1.jpg",
    secondImgs: [
      { id: 1, secondImg: "assets/proImg/logos/2/1.jpg" },
      { id: 2, secondImg: "assets/proImg/logos/2/2.png" },
      { id: 3, secondImg: "assets/proImg/logos/2/3.jpg" },
      { id: 4, secondImg: "assets/proImg/logos/2/4.jpg" },
      { id: 5, secondImg: "assets/proImg/logos/2/5.jpg" },
    ],
    link: "https://www.behance.net/gallery/137597355/Marketing-Agency",
    desc: "it is a Marketing Agency to provide all marketing services for products such as (Photography - Graphic Designs - Motion Graphics - E-Marketing)",
  },
  {
    id: 3,
    title: "moony",
    mainImg: "assets/proImg/logos/3/1.jpg",
    secondImgs: [
      { id: 1, secondImg: "assets/proImg/logos/3/1.jpg" },
      { id: 2, secondImg: "assets/proImg/logos/3/2.jpg" },
      { id: 3, secondImg: "assets/proImg/logos/3/3.jpg" },
      { id: 4, secondImg: "assets/proImg/logos/3/4.jpg" },
      { id: 5, secondImg: "assets/proImg/logos/3/5.png" },
    ],
    link: "https://www.behance.net/gallery/137596569/lenses-Brand-logo",
    desc: "lenses Brand",
  },
  {
    id: 4,
    title: "Clouds",
    mainImg: "assets/proImg/logos/4/1.jpg",
    secondImgs: [
      { id: 1, secondImg: "assets/proImg/logos/4/1.jpg" },
      { id: 2, secondImg: "assets/proImg/logos/4/2.jpg" },
      { id: 3, secondImg: "assets/proImg/logos/4/3.png" },
      { id: 4, secondImg: "assets/proImg/logos/4/4.png" },
    ],
    link: "https://www.behance.net/gallery/137595141/Beauty-salon",
    desc: "It is a beauty salon",
  },
  {
    id: 5,
    title: "Technical solutions",
    mainImg: "assets/proImg/logos/5/1.jpg",
    secondImgs: [
      { id: 1, secondImg: "assets/proImg/logos/5/1.jpg" },
      { id: 2, secondImg: "assets/proImg/logos/5/2.jpg" },
      { id: 3, secondImg: "assets/proImg/logos/5/3.png" },
      { id: 4, secondImg: "assets/proImg/logos/5/4.jpg" },
      { id: 5, secondImg: "assets/proImg/logos/5/5.jpg" },
      { id: 6, secondImg: "assets/proImg/logos/5/6.png" },
    ],
    link: "https://www.behance.net/gallery/137594859/technical-solutions-logo",
    desc: "It is a company that provides administrative and technical consultancy, formulation and implementation of restructuring plans and administrative organization",
  },
  {
    id: 6,
    title: "osam",
    mainImg: "assets/proImg/logos/6/1.jpg",
    secondImgs: [
      { id: 1, secondImg: "assets/proImg/logos/6/1.jpg" },
      { id: 2, secondImg: "assets/proImg/logos/6/2.jpg" },
      { id: 3, secondImg: "assets/proImg/logos/6/3.jpg" },
      { id: 4, secondImg: "assets/proImg/logos/6/4.jpg" },
      { id: 5, secondImg: "assets/proImg/logos/6/5.jpg" },
      { id: 6, secondImg: "assets/proImg/logos/6/6.jpg" },
    ],
    link: "https://www.behance.net/gallery/137594229/Candies-shop-logo",
    desc: "A sweets shop that serves sweets and hot drinks",
  },
];

export const labels = [
  {
    id: 1,
    title: "Medrex cream",
    mainImg: "assets/proImg/Labels/1/1.jpg",
    brandLogo: "assets/proImg/Labels/1/logo.png",
    secondImgs: [
      { id: 1, secondImg: "assets/proImg/Labels/1/1.jpg" },
      { id: 2, secondImg: "assets/proImg/Labels/1/2.jpg" },
    ],
    link: "http:",
    desc: "massage cream",
  },
  {
    id: 2,
    title: "vito ointmen",
    mainImg: "assets/proImg/Labels/2/1.png",
    brandLogo: "assets/proImg/Labels/2/logo.png",
    secondImgs: [
      { id: 1, secondImg: "assets/proImg/Labels/2/1.png" },
      { id: 2, secondImg: "assets/proImg/Labels/2/2.jpg" },
    ],
    link: "http:",
    desc: "ointment for skin care produced by Shifa Al sharkia Medical Establishment.",
  },
  {
    id: 3,
    title: "Sakkara",
    mainImg: "assets/proImg/Labels/3/1.jpg",
    brandLogo: "assets/proImg/Labels/3/logo.png",
    secondImgs: [
      { id: 1, secondImg: "assets/proImg/Labels/3/1.jpg" },
      { id: 2, secondImg: "assets/proImg/Labels/3/2.jpg" },
      { id: 3, secondImg: "assets/proImg/Labels/3/3.jpg" },
      { id: 4, secondImg: "assets/proImg/Labels/3/4.jpg" },
      { id: 5, secondImg: "assets/proImg/Labels/3/5.jpg" },
      { id: 6, secondImg: "assets/proImg/Labels/3/6.jpg" },
    ],
    link: "http:",
    desc: "It is a company that produces natural oils to treat dental problems",
  },
];

export const videos = [
  {
    id: 1,
    mainImg: "assets/proImg/videos/1.mp4",
    secondImgs: [],
    type: "video",
  },
  {
    id: 2,
    mainImg: "assets/proImg/videos/2.mp4",
    secondImgs: [],
    type: "video",
  },
  {
    id: 3,
    mainImg: "assets/proImg/videos/3.mp4",
    secondImgs: [],
    type: "video",
  },
  {
    id: 4,
    mainImg: "assets/proImg/videos/4.mp4",
    secondImgs: [],
    type: "video",
  },
  {
    id: 5,
    mainImg: "assets/proImg/videos/5.mp4",
    secondImgs: [],
    type: "video",
  },
  {
    id: 6,
    mainImg: "assets/proImg/videos/6.mp4",
    secondImgs: [],
    type: "video",
  },
  {
    id: 7,
    mainImg: "assets/proImg/videos/7.mp4",
    secondImgs: [],
    type: "video",
  },
  {
    id: 8,
    mainImg: "assets/proImg/videos/8.mp4",
    secondImgs: [],
    type: "video",
  },
];
